services:
  upload_server:
    container_name: upload_server
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3333"
    environment:
      - ENVIRONMENT=development
    env_file:
      - .env
    depends_on:
      - upload_server_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["pnpm", "dev"]
  upload_server_db:
    container_name: upload_server_db
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=upload
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - ./.ignore/postgres/:/bitnami/postgresql
